#ifndef APP_EPSCFG_HPP
#define APP_EPSCFG_HPP

enum IndexEPSTLM {
    EPSCMD = 0,
    EPSSTATUS = 1,
    EPSVBATT = 26,
    EPSTEMP = 205,
    EPSBATTMODE = 231
};

enum EPSPort{
    EPS_DIRECT_CONTROL_PORT = 14,
    EPS_CONF_MGMT_PORT = 15,
    EPS_RESET_PORT_PORT = 16,
    EPS_INST_TLM_PORT = 7,
    EPS_TIME_SYNC_PORT = 8
};


enum EPSParam{
    EPS_LIMIT_LOW_BATTERY = 10,
    EPS_LIMIT_TEMP_HIGH = 100
};
#endif //REF_SOCKETIPDRIVERCFG_HPP
