#ifndef APP_SOCKETCSPDRIVERCFG_HPP
#define APP_SOCKETCSPDRIVERCFG_HPP

enum SocketCspCfg {
    UDPPort = 10,
    MAX_SIZE_PACKET = 256,
    MAX_HOSTNAME_SIZE = 256
};



#endif //REF_SOCKETIPDRIVERCFG_HPP
