#ifndef APP_SOCKETCSPDRIVERCFG_HPP
#define APP_SOCKETCSPDRIVERCFG_HPP

enum SocketCspCfg {
    CSP_UDPPort = 10,
    CSP_MAX_SIZE_PACKET = 256,
    CSP_MAX_HOSTNAME_SIZE = 256,
    CSP_TIMEOUT = 1000
};



#endif //REF_SOCKETIPDRIVERCFG_HPP
