/**
 *  PUSopen(R) Mission Database
 *  
 *  THIS FILE HAS BEEN AUTOGENERATED.
 *  ANY MANUAL MODIFICATIONS MAY BE OVERWRITTEN.
 */

/* Include files */
#include "pusopen.h"

/* Included PUSopen(R) modules */

#define PUS1_PROVIDER
/* #define PUS3_PROVIDER */
/* #define PUS5_PROVIDER */
/* #define PUS8_PROVIDER */
/* #define PUS13_PROVIDER */
/* #define PUS17_PROVIDER */
#define PUS_USR

/* PUSopen(R) configuration */

/* PUS 1 - Size of reception buffer (in bytes) */
#define PUS1_RECV_BUF_SIZE		2048

/* PUS 1 - Virtual Channel for TM[1,x] */
#define PUS1_VCID		1

/* PUS Service User - Size of send buffer (in bytes) */
#define PUSUSR_SEND_BUF_SIZE		1

/* PUS Service User - Virtual Channel for TC */
#define PUSUSR_VCID		1

/* PUS Service User - TM header type */
#define PUSUSR_TM_HDR_TYPE		ECSS_E_ST_70_41C

/* PUS Service User - TM header length */
#define PUSUSR_TM_HDR_LEN		11

#define PS_LAYER

/* PS - Max size of sent packet (in bytes) */
#define PS_MAX_SEND_PACKET_SIZE		2048

/* PS - Max size of received packet (in bytes) */
#define PS_MAX_RECV_PACKET_SIZE		2048

/* PS - Checksum type */
#define PS_PKT_CHECKSUM_TYPE		PKT_ISO16

/* PS - Checksum length (in bytes) */
#define PS_PKT_CHECKSUM_LEN		2

#define FESS_LAYER

/* FESS - Size of send buffer (in bytes) */
#define FESS_SEND_BUF_SIZE		2048

/* FESS - Size of reception buffer (in bytes) */
#define FESS_RECV_BUF_SIZE		2048

/* FESS - Size of FESS temporary buffers (in bytes) */
#define FESS_TEMP_BUF_SIZE		2048

/* FESS - Attached Synchronization Mark (ASM) */
#define FESS_ASM		FESS_DEF_ASM

/* FESS - Length of ASM */
#define FESS_ASM_LEN		3

/* FESS - Frame encoding algorithm */
#define FESS_ENCODING		SLIP

/* FESS - Frame encryption algorithm */
#define FESS_ENCRYPTION		NOENCRYPTION

/* FESS - AES128 encryption key */
#define FESS_AES_KEY		{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0}

/* FESS - AES128 initial vector */
#define FESS_AES_IV		{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0}

/* PUS Service providers and user */

#ifdef PUS1_PROVIDER
PUS1_PROVIDER_INIT(pus1, PUS1_RECV_BUF_SIZE, PUS1_VCID);
#endif

#ifdef PUS_USR
PUSUSR_INIT(pusUsr, PUSUSR_SEND_BUF_SIZE, PUSUSR_VCID, PUSUSR_TM_HDR_TYPE, PUSUSR_TM_HDR_LEN);
#endif

/* Packet Services */

#ifdef PS_LAYER
PS_INIT(ps, PS_MAX_SEND_PACKET_SIZE, PS_MAX_RECV_PACKET_SIZE, PS_PKT_CHECKSUM_TYPE, PS_PKT_CHECKSUM_LEN);
#endif


/* FESS Layer */

#ifdef FESS_LAYER
FESS_INIT(fess, FESS_ASM, FESS_ASM_LEN, FESS_ENCODING, FESS_ENCRYPTION, FESS_SEND_BUF_SIZE, FESS_RECV_BUF_SIZE, FESS_TEMP_BUF_SIZE, FESS_TEMP_BUF_SIZE, FESS_TEMP_BUF_SIZE, FESS_TEMP_BUF_SIZE, FESS_AES_KEY, FESS_AES_IV);
#endif

/* User Code */



/* On-board Events */

po_evt_t evt[] = {
};

/* User Functions */

po_fnc_t fnc[] = {
};

/* HK Parameters */

po_obparam_t obparams[] = {
#ifdef FESS_LAYER
PO_MDB_PARAMS_FESS
#endif
#ifdef PS_LAYER
PO_MDB_PARAMS_PS
#endif
#ifdef VC_LAYER
PO_MDB_PARAMS_VC
#endif
#ifdef PUS1_PROVIDER
PO_MDB_PARAMS_PUS1
#endif
#ifdef PUS3_PROVIDER
PO_MDB_PARAMS_PUS3
#endif
#ifdef PUS5_PROVIDER
PO_MDB_PARAMS_PUS5
#endif
#ifdef PUS8_PROVIDER
PO_MDB_PARAMS_PUS8
#endif
#ifdef PUS13_PROVIDER
PO_MDB_PARAMS_PUS13
#endif
#ifdef PUS17_PROVIDER
PO_MDB_PARAMS_PUS17
#endif
#ifdef PUS_USR
PO_MDB_PARAMS_PUSUSR
#endif
};

/* HK Reports */

po_hkreport_t hkreps[] = {
};

/* PUSopen(R) Mission Database */

po_mdbapid_t po_mdb_apid = {
    .apid = 3,
    .apuid = 4,

    .pus1  = POADDR(pus1),
    .pus3 = PONULL,
    .pus5 = PONULL,
    .pus8 = PONULL,
    .pus13 = PONULL,
    .pus17 = PONULL,
    .pusUsr  = POADDR(pusUsr),
    .ps  = POADDR(ps),
    .vc = PONULL,
    .fess  = POADDR(fess),

    .numevt = 0U,
    .numparams = 19U,
    .numreports = 0U,
    .numfct = 0U,
    .events = evt,
    .obparams = obparams,
    .func = fnc,
    .hkreports = hkreps
};

/**
 *  Default implementation of pususr_tm to satisfy
 *  dependencies if PUS Service User is not used.
 */
#ifndef PUS_USR
EMPTY_PUSUSR_TM
#endif

/**
 *  Default implementation of po_time to satisfy
 *  dependencies if user does not implement po_time.
 */
#ifndef PUS_CUSTOM_TIME
EMPTY_PO_TIME
#endif

/**
 *  Default implementation of po_tc to satisfy
 *  dependencies if user does not implement po_tc.
 */
#ifndef PUS_CUSTOM_SERVICES
EMPTY_PO_TC
#endif

/**
 *  Default implementation of pus13_tc to satisfy
 *  dependencies if user does not implement pus13_tc.
 */
#ifndef PUS13_PROVIDER
EMPTY_PUS13_TC
#endif

/**
 *  Default implementation Subnetwork functions
 *  to satisfy libps dependencies.
 */
#ifdef NO_SUBNET
EMPTY_SUBNET
#endif

/* MDB format version */
#define MDB_VERSION		1
