name: Continous delivery

on:
  push:
    #branches: [ main ]

env:
  path: App
  delivery-path: ~/fsw/chess

jobs:
  delivery:
    runs-on: self-hosted
    name: Delivery
    
    steps:
      # checkout the repository
      - uses: actions/checkout@v2

      # Init the virtual environnement (project script)
      - name: Prepare venv
        run: ./scripts/init-venv.sh

      # Build the project (project script)
      - name: Build the project
        run: ./scripts/build.sh ${{env.path}}

      # Put the build-artifacts folder at the "latest"
      - name: Put version as latest
        run: |
          find ${{ env.delivery-path }}/latest/* -delete || true
          cp -r ${{env.path}}/build-artifacts ${{env.delivery-path}}/latest

      #put the build-artifacts folder as archive
      - name: Put verson in archive
        run: cp -r ${{env.path}}/build-artifacts ${{env.delivery-path}}/archives/$(date +"%d_%m_%Y_%H:%M:%S")